In [ ]:
import gymnasium as gym
from minigrid.envs import FourRoomsEnv, LavaGapEnv, LockedRoomEnv
import time
from minigrid.rendering.rendering_manager import RenderingManager
from minigrid.rendering.smooth_rendering_manager import SmoothRenderingManager
import numpy as np

env = LockedRoomEnv(render_mode='human', rendering_manager=SmoothRenderingManager)

observation, info = env.reset()
for _ in range(250):

    rand = np.random.rand()
    action = 2

    if rand < 0.3:
        action = env.action_space.sample()

    observation, reward, terminated, truncated, info = env.step(action)

    if terminated or truncated:
        observation, info = env.reset()

    # pause for a few milliseconds before rendering the next frame
    time.sleep(0.05)
    
env.close()

: 

In [1]:
import pyglet
from pyglet.image import ImageGrid

environments_sprite_sheet = pyglet.image.load('sprites/oryx_16bit_walls.png')
environments_grid = ImageGrid(environments_sprite_sheet, rows=23, columns=27, row_padding=0, column_padding=0)

# all sprites from row 19 starting from bottom left corner
access_row = 18
env_tiles = [environments_grid[(27 * access_row) + i] for i in range(27)]

wall_tiles = env_tiles[:3] + env_tiles[9:]

# wall tile mapping

WALL_TYPES = {
    (0,0,0,
     0,2,0,
     0,0,0) : (0,1), # Single standalone wall
    (0,0,0,
     0,2,2,
     0,0,0) : (4,4), # Left cap wall (horizontal)
    (0,0,0,
     2,2,2,
     0,0,0) : (5,20), # Horizontal wall segment
    (0,0,0,
     2,2,0,
     0,0,0) : (6,6), # Right cap wall (horizontal)
    (0,0,0,
     0,2,0,
     0,2,0) : (7,7), # Top cap wall (vertical)
    (0,2,0,
     0,2,0,
     0,2,0) : (8,19), # Vertical wall segment
    (0,2,0,
     0,2,0,
     0,0,0) : (9,9), # Bottom cap wall (vertical)
    (0,0,0,
     0,2,2,
     0,2,0) : (10,10), # Top-left corner wall
    (0,0,0,
     2,2,0,
     0,2,0) : (11,11), # Top-right corner wall
    (0,2,0,
     0,2,2,
     0,0,0) : (12,12), # Bottom-left corner wall
    (0,2,0,
     2,2,0,
     0,0,0) : (13,13), # Bottom-right corner wall
    (0,2,0,
     2,2,2,
     0,2,0) : (14,14), # Cross intersection wall
    (0,0,0,
     2,2,2,
     0,2,0) : (15,15), # T-junction wall (top-open)
    (0,2,0,
     2,2,0,
     0,2,0) : (16,16), # T-junction wall (right-open)
    (0,2,0,
     0,2,2,
     0,2,0) : (17,17), # T-junction wall (left-open)
    (0,2,0,
     2,2,2,
     0,0,0) : (18,18), # T-junction wall (bottom-open)
}

# Create sprites for each tile in WALL_TYPES
sprites = []
x_offset = 50  # Start position
y_offset = 300  # Vertical position for all sprites
spacing = 36    # Spacing between tiles

for tile_indices in WALL_TYPES.values():
    tile_index = tile_indices[0]  # Use the first index in the tuple
    wall_image = wall_tiles[tile_index]
    sprite = pyglet.sprite.Sprite(wall_image, x=x_offset, y=y_offset)
    sprites.append(sprite)
    x_offset += spacing  # Move to the right for the next sprite

# Create a Pyglet window
window = pyglet.window.Window(width=800, height=600)


@window.event
def on_draw():
    # Clear the window
    window.clear()

    # Draw each sprite
    for sprite in sprites:
        sprite.draw()


# Close the window after 10 seconds
def close_window(dt):
    window.close()


# Schedule window closure
pyglet.clock.schedule_once(close_window, 10)  # Close after 10 seconds

# Run the Pyglet application
pyglet.app.run()

GLException: (0x1282): Invalid operation. The specified operation is not allowed in the current state.

In [4]:
window.close()

In [ ]:
import gymnasium as gym
from minigrid.envs import FourRoomsEnv, LavaGapEnv, LockedRoomEnv
import time
from minigrid.rendering.rendering_manager import RenderingManager
from minigrid.rendering.smooth_rendering_manager import SmoothRenderingManager
import numpy as np

env = LockedRoomEnv(render_mode='human', rendering_manager=SmoothRenderingManager)

grid = env.grid

encoding = grid.encode()

for i in range(10):
    print(encoding[i])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]
[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]
[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]
[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]
[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]
[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0

In [30]:
from minigrid.core.world_object import Ball
import ctypes
import numpy as np

# Original grid: a 3x3 list of Ball objects
grid = [[Ball() for _ in range(3)] for _ in range(3)]

# Create a flat NumPy array of ctypes pointers to the objects in the grid
pointer_array = np.empty((3, 3), dtype=object)
for i in range(3):
    for j in range(3):
        pointer_array[i, j] = ctypes.pointer(ctypes.py_object(grid[i][j]))

print("Original color:", grid[0][0].color)

# Access and modify elements in the grid
grid[0][0] = Ball(color="red")

# Access elements via the pointer array
print("Direct grid access:", grid[0][0].color)  # Should print "red"
print("Pointer array access:", pointer_array[0, 0].contents.value.color)  # Should also print "red"



Original color: blue
Direct grid access: red
Pointer array access: blue


In [3]:
import numpy as np

# create a 3x3 grid of numbers from 0 to 8
grid = np.arange(9).reshape(3, 3)

print("Original grid:")
print(grid)

# Create view of subset of the grid
view = grid[1:, 1:].view()

# Modify the view
view[0, 0] = 100

print("Modified grid:")
print(grid)

print("View:")
print(view)

Original grid:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Modified grid:
[[  0   1   2]
 [  3 100   5]
 [  6   7   8]]
View:
[[100   5]
 [  7   8]]


In [1]:
import pyglet as pg

# Create a window
window = pg.window.Window()

# Create a label
label = pg.text.Label('Hello, world',
                      font_name='Times New Roman',
                      font_size=36,
                      x=window.width // 2, y=window.height // 2,
                      anchor_x='center', anchor_y='center')

# Sprite with basic image
image = pg.image.load('figures/sprites/Chest_Open_Filled.png')
sprite = pg.sprite.Sprite(image, x=100, y=0)

# Load the sprite sheet
chest_opening_sheet = pg.image.load('figures/sprites/Chest_Open_Empty.png')

# Create animation frames
frames = []
for i in range(4):
    frame_image = chest_opening_sheet.get_region(i * 16, 0, 16, 16)
    animation_frame = pg.image.AnimationFrame(frame_image, duration=0.1)  # Set a duration for each frame
    frames.append(animation_frame)

# Create animation
animation = pg.image.Animation(frames)

# Create animated sprite
anim_sprite = pg.sprite.Sprite(animation, x=200, y=0)

# Function to render all sprites
def render_sprites():
    window.clear()
    label.draw()
    sprite.draw()
    anim_sprite.draw()

# Event to draw the window
@window.event
def on_draw():
    render_sprites()

# Example of calling the render function
def main_loop():
    for _ in range(4):
        render_sprites()
        pg.clock.tick( 60 )

# Run the application
pg.app.run()

# Call the main loop to render the sprites
main_loop()

GLException: (0x1282): Invalid operation. The specified operation is not allowed in the current state.

In [4]:
# close all windows
pg.app.exit()